apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-untrust
      - op: replace
        path: /metadata/labels/run
        value: nginx-untrust
    target:
      labelSelector: "run=nginx"
